# Generated by Django 5.2.18 on 2026-10-07 10:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'ይህ ደንበኛ አስቀድሞ ተመዝግቧል።'}, max_length=120, unique=True, verbose_name='የደንበኛ ስም')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='ስልክ')),
                ('demo', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)], verbose_name='ዓ.ም')),
                ('m', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='ወር')),
                ('d', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='ቀን')),
                ('demo', models.BooleanField(default=False, help_text='ምሳሌ መረጃ ምልክት')),
                ('cat', models.CharField(max_length=80, verbose_name='የወጪ ዓይነት')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ማብራሪያ')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['-y', '-m', '-d', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'ይህ ዕቃ አስቀድሞ ተመዝግቧል።'}, max_length=120, unique=True, verbose_name='የዕቃ ስም')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='መለኪያ')),
                ('buy', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('sell', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('init', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('low', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('demo', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='የእኔ ሱቅ', max_length=120, verbose_name='የሱቅ ስም')),
                ('title_am', models.CharField(blank=True, default='አብሮስ ህትመት ስራ', max_length=120)),
                ('title_en', models.CharField(blank=True, default='ABROS PRINTING WORK', max_length=120)),
                ('website', models.CharField(blank=True, default='www.abrosprint.com', max_length=120)),
                ('phone', models.CharField(blank=True, default='+251 955 33 15 33', max_length=60)),
                ('handle', models.CharField(blank=True, default='@abrosdesign', max_length=80)),
                ('social', models.CharField(blank=True, default='@abrsodesign', max_length=80)),
                ('signer', models.CharField(blank=True, default='Yohannes Tadu', max_length=120)),
                ('signer_role', models.CharField(blank=True, default='G.MANAGER', max_length=80)),
                ('tot_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('terms', models.TextField(blank=True, default='The price and terms of this offer are valid for 20 days from date of this proposal.')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('pr_terms', models.TextField(blank=True, default='Payment is requested according to the agreed terms and the amount shown above.')),
            ],
            options={
                'verbose_name_plural': 'shop settings',
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)], verbose_name='ዓ.ም')),
                ('m', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='ወር')),
                ('d', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='ቀን')),
                ('demo', models.BooleanField(default=False, help_text='ምሳሌ መረጃ ምልክት')),
                ('seq', models.PositiveIntegerField(verbose_name='ተራ ቁጥር')),
                ('client', models.CharField(blank=True, max_length=160, verbose_name='ደንበኛ')),
            ],
            options={
                'ordering': ['-y', '-m', '-d', '-id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('y', 'seq'), name='uniq_delivery_year_seq')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ledger.deliverynote')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)], verbose_name='ዓ.ም')),
                ('m', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='ወር')),
                ('d', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='ቀን')),
                ('demo', models.BooleanField(default=False, help_text='ምሳሌ መረጃ ምልክት')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ማስታወሻ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ledger.customer')),
            ],
            options={
                'ordering': ['-y', '-m', '-d', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)], verbose_name='ዓ.ም')),
                ('m', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='ወር')),
                ('d', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='ቀን')),
                ('demo', models.BooleanField(default=False, help_text='ምሳሌ መረጃ ምልክት')),
                ('seq', models.PositiveIntegerField(verbose_name='ተራ ቁጥር')),
                ('client', models.CharField(blank=True, max_length=160, verbose_name='ደንበኛ')),
                ('due_y', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)], verbose_name='መክፈያ ዓ.ም')),
                ('due_m', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='መክፈያ ወር')),
                ('due_d', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='መክፈያ ቀን')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='VAT %')),
                ('terms', models.TextField(blank=True, verbose_name='Terms and conditions')),
            ],
            options={
                'ordering': ['-y', '-m', '-d', '-id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('y', 'seq'), name='uniq_payreq_year_seq')],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ledger.paymentrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)], verbose_name='ዓ.ም')),
                ('m', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='ወር')),
                ('d', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='ቀን')),
                ('demo', models.BooleanField(default=False, help_text='ምሳሌ መረጃ ምልክት')),
                ('seq', models.PositiveIntegerField(verbose_name='ተራ ቁጥር')),
                ('client', models.CharField(blank=True, max_length=160, verbose_name='ደንበኛ')),
                ('tot_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='TOT %')),
                ('terms', models.TextField(blank=True, verbose_name='Terms and conditions')),
            ],
            options={
                'ordering': ['-y', '-m', '-d', '-id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('y', 'seq'), name='uniq_proforma_year_seq')],
            },
        ),
        migrations.CreateModel(
            name='ProformaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ledger.proforma')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)], verbose_name='ዓ.ም')),
                ('m', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='ወር')),
                ('d', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='ቀን')),
                ('demo', models.BooleanField(default=False, help_text='ምሳሌ መረጃ ምልክት')),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('supplier', models.CharField(blank=True, max_length=120, verbose_name='አቅራቢ')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='ledger.item')),
            ],
            options={
                'ordering': ['-y', '-m', '-d', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)], verbose_name='ዓ.ም')),
                ('m', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='ወር')),
                ('d', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='ቀን')),
                ('demo', models.BooleanField(default=False, help_text='ምሳሌ መረጃ ምልክት')),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('cash', 'ጥሬ ገንዘብ'), ('credit', 'ዱቤ')], default='cash', max_length=10)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='ledger.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='ledger.item')),
            ],
            options={
                'ordering': ['-y', '-m', '-d', '-id'],
                'abstract': False,
            },
        ),
    ]
