# Generated by Django 5.2.18 on 2026-10-07 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)], verbose_name='ዓ.ም')),
                ('m', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='ወር')),
                ('d', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='ቀን')),
                ('demo', models.BooleanField(default=False, help_text='ምሳሌ መረጃ ምልክት')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('kind', models.CharField(choices=[('own', 'ያለ ዕዳ'), ('debt', 'በዕዳ')], default='own', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='ምክንያት')),
            ],
            options={
                'ordering': ['-y', '-m', '-d', '-id'],
                'abstract': False,
            },
        ),
    ]
