# Generated by Django 5.2.18 on 2026-10-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_bankentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankentry',
            name='rep_d',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankentry',
            name='rep_m',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankentry',
            name='rep_y',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankentry',
            name='repaid',
            field=models.BooleanField(default=False),
        ),
    ]
