// አማርኛ → English ትርጉም። ቁልፉ በኮዱ ውስጥ ያለው አማርኛ ጽሑፍ ነው።
export default {
  "ሽያጭ": "Sales",
  "{n} ግብይቶች · {v} ብር": "{n} transactions · {v} ETB",
  "አዲስ ሽያጭ": "New sale",
  "በዚህ ጊዜ ሽያጭ የለም።": "No sales in this period.",
  "ቀን": "Date",
  "ዕቃ": "Item",
  "ብዛት": "Qty",
  "ዋጋ": "Price",
  "ጠቅላላ": "Total",
  "ትርፍ": "Profit",
  "አይነት": "Type",
  "ዱቤ": "Credit",
  "ጥሬ": "Cash",
  "አስተካክል": "Edit",
  "ድምር": "Total",
  "ሽያጭ አስተካክል": "Edit sale",
  "በክምችት ያለ፦ {v}": "In stock: {v}",
  "— ይምረጡ —": "— Select —",
  "የአንዱ ዋጋ": "Unit price",
  "ጥሬ ገንዘብ": "Cash",
  "ደንበኛ": "Customer",
  "ቅድመ ክፍያ": "Down payment",
  "ዛሬ የተከፈለ ካለ": "If anything was paid today",
  "ብር": "ETB",
  "ተው": "Cancel",
  "አስቀምጥ": "Save",
  "ዕዳ": "Debts",
  "{n} ተበዳሪዎች · {v} ብር ይቀራል": "{n} debtors · {v} ETB outstanding",
  "አዲስ ደንበኛ": "New customer",
  "ክፍያ መዝግብ": "Record payment",
  "ደንበኞች": "Customers",
  "ክፍያዎች": "Payments",
  "ገና ደንበኛ አልተመዘገበም።": "No customers yet.",
  "ስልክ": "Phone",
  "የተከፈለ": "Paid",
  "ቀሪ": "Balance",
  "ተከፍሏል": "Settled",
  "ክፍያ": "Pay",
  "በዚህ ጊዜ ክፍያ የለም።": "No payments in this period.",
  "ማስታወሻ": "Note",
  "መጠን": "Amount",
  "ደንበኛ አስተካክል": "Edit customer",
  "ክፍያ አስተካክል": "Edit payment",
  "ስም": "Name",
  "የተከፈለ መጠን": "Amount paid",
  "ቤት ኪራይ": "Rent",
  "ደመወዝ": "Salaries",
  "መብራት/ውሃ": "Electricity/Water",
  "ትራንስፖርት": "Transport",
  "ማስታወቂያ": "Advertising",
  "ጥገና": "Maintenance",
  "ግብር": "Tax",
  "ሌላ": "Other",
  "ወጪ": "Expenses",
  "ወጪ መዝግብ": "Record expense",
  "በዚህ ጊዜ ወጪ የለም።": "No expenses in this period.",
  "ዓይነት": "Category",
  "ወጪ አስተካክል": "Edit expense",
  "የወጪ ዓይነት": "Expense category",
  "የናሙና መረጃ ተጭኗል": "Sample data loaded",
  "የናሙና መረጃ ተሰርዟል": "Sample data removed",
  "ቅንብር": "Settings",
  "የሱቅና የፕሮፎርማ መረጃ": "Shop and document details",
  "የሱቅ ስም": "Shop name",
  "ርዕስ (አማርኛ)": "Title (Amharic)",
  "ርዕስ (English)": "Title (English)",
  "ድረ-ገጽ / ኢሜይል": "Website / Email",
  "ፈራሚ": "Signer",
  "የፈራሚ ሥራ": "Signer's role",
  "ነባሪ VAT %": "Default VAT %",
  "ነባሪ VAT %": "Default VAT %",
  "ነባሪ Terms (ፕሮፎርማ)": "Default terms (Proforma)",
  "ነባሪ Terms (የክፍያ ጥያቄ)": "Default terms (Payment Request)",
  "ቋንቋ": "Language",
  "ገጽታ": "Theme",
  "ብርሃን": "Light",
  "ጨለማ": "Dark",
  "የናሙና መረጃ": "Sample data",
  "ናሙና ጫን": "Load sample",
  "ናሙና ሰርዝ": "Remove sample",
  "ናሙና የሚጫነው ደብተሩ ባዶ ሲሆን ብቻ ነው፤ መሰረዝ የናሙናውን ብቻ ያጠፋል። ገጹን ያድሱ።": "Sample data loads only when the ledger is empty; removing it deletes only the sample. Refresh the page afterwards.",
  "መለያ": "Account",
  "ውጣ": "Log out",
  "ተሰርዟል": "Deleted",
  "{n} ሰነዶች": "{n} documents",
  "ገና ሰነድ አልተፈጠረም።": "No documents yet.",
  "ቁጥር": "No.",
  "መክፈያ ቀን": "Due date",
  "ክፈት": "Open",
  "ዝርዝር": "List",
  "አትም / PDF": "Print / PDF",
  "በህትመት መስኮቱ “Save as PDF” ይምረጡ።": "In the print dialog choose “Save as PDF”.",
  "ቢያንስ አንድ ዕቃ ያስገቡ።": "Add at least one item.",
  "አስተካክል · {n}": "Edit · {n}",
  "ተመለስ": "Back",
  "ደንበኛ (Invoice to)": "Client (Invoice to)",
  "መክፈያ ቀን (Payment Due)": "Payment due date",
  "ዕቃዎች": "Items",
  "አስወግድ": "Remove",
  "መስመር ጨምር": "Add line",
  "በማስቀመጥ ላይ…": "Saving…",
  "አስቀምጥና ክፈት": "Save and open",
  "ክምችት": "Stock",
  "{n} ዕቃዎች · ዋጋ {v} ብር": "{n} items · worth {v} ETB",
  "አዲስ ዕቃ": "New item",
  "ግዢ መዝግብ": "Record purchase",
  "ግዢዎች": "Purchases",
  "ገና ዕቃ አልተመዘገበም።": "No items yet.",
  "ሁኔታ": "Status",
  "መግዣ": "Buy",
  "መሸጫ": "Sell",
  "የክምችት ዋጋ": "Stock value",
  "በዚህ ጊዜ ግዢ የለም።": "No purchases in this period.",
  "አቅራቢ": "Supplier",
  "ዕቃ አስተካክል": "Edit item",
  "ግዢ አስተካክል": "Edit purchase",
  "የዕቃ ስም": "Item name",
  "መለኪያ": "Unit",
  "ሊያልቅ ሲል ማስጠንቀቂያ": "Low-stock alert",
  "ቀሪው ከዚህ ሲያንስ": "When remaining falls below this",
  "መግዣ ዋጋ": "Buy price",
  "መሸጫ ዋጋ": "Sell price",
  "መጀመሪያ ክምችት": "Opening stock",
  "ፍሬ": "pcs",
  "ገና መረጃ የለም።": "No data yet.",
  "ዳሽቦርድ": "Dashboard",
  "ሽያጭ መዝግብ": "Record sale",
  "ዕቃ ጨምር": "Add item",
  "የናሙና መረጃ ጫን": "Load sample data",
  "ደብተሩ ባዶ ነው። ዕቃ በመጨመር ይጀምሩ ወይም ናሙና ይጫኑ።": "The ledger is empty. Start by adding items or load sample data.",
  "የዛሬ ሽያጭ": "Today's sales",
  "የ{month} ሽያጭ": "{month} sales",
  "ጠቅላላ ትርፍ {v}": "Gross profit {v}",
  "የወሩ የተጣራ ትርፍ": "Net profit this month",
  "ወጪ {v}": "Expenses {v}",
  "የዓመቱ የተጣራ ትርፍ": "Net profit this year",
  "ሽያጭ {v}": "Sales {v}",
  "ጠቅላላ ዕዳ": "Total debt",
  "{n} ተበዳሪዎች": "{n} debtors",
  "ሊያልቁ የተቃረቡ": "Running low",
  "ወርሃዊ ሽያጭ · {y}": "Monthly sales · {y}",
  "የዕቃ ዋጋ": "Cost of goods",
  "የተጣራ ትርፍ በወር": "Net profit by month",
  "ብዙ የተሸጡ": "Best sellers",
  "ብዙ ትርፍ ያመጡ": "Most profitable",
  "ክምችት ማስጠንቀቂያ": "Stock alerts",
  "ሁሉም ዕቃ በቂ ነው።": "All items are well stocked.",
  "ደ": "L",
  "ዲጂታል የሱቅ ደብተር": "Digital Shop Ledger",
  "እንኳን ደህና መጡ": "Welcome",
  "የተጠቃሚ ስም": "Username",
  "የይለፍ ቃል": "Password",
  "በመግባት ላይ…": "Signing in…",
  "ግባ": "Sign in",
  "በቂ": "In stock",
  "ሊያልቅ ነው": "Low",
  "አልቋል": "Out of stock",
  "ሰርዝ": "Delete",
  "እርግጠኛ ነዎት?": "Are you sure?",
  "ወር": "Month",
  "ዓ.ም": "Year",
  "ዝጋ": "Close",
  "እንደገና ሞክር": "Retry",
  "ሁሉም ወራት": "All months",
  "ፕሮፎርማ": "Proforma",
  "የክፍያ ጥያቄ": "Payment Request",
  "የሱቅ ደብተር": "Shop Ledger",
  "አዲስ ፕሮፎርማ": "New proforma",
  "አዲስ የክፍያ ጥያቄ": "New payment request",
  "ከአገልጋዩ ጋር መገናኘት አልተቻለም።": "Could not reach the server.",
  "ስህተት ተፈጠረ ({s})።": "Something went wrong ({s}).",
  "የማድረሻ ሰነድ": "Delivery Note",
  "አዲስ የማድረሻ ሰነድ": "New delivery note",
  "ደንበኛ (Customer)": "Customer",
  "የካፒታል ሒሳብ": "Capital balance",
  "ከመነሻው {v}": "{v} since start",
  "የገንዘብ ሒሳብ": "Cash balance",
  "በእጅ/በባንክ ያለ": "Cash on hand & in bank",
  "የወሩ ገንዘብ ገቢ": "Cash in this month",
  "የወሩ ገንዘብ ወጪ": "Cash out this month",
  "የተጣራ ፍሰት {v}": "Net flow {v}",
  "የካፒታል ስብጥር": "Capital breakdown",
  "ተቀባይ ዕዳ": "Receivables (customer debts)",
  "መነሻ ካፒታል": "Starting capital",
  "ዕድገት": "Growth",
  "የገንዘብ ሒሳብ በወር መጨረሻ": "Cash balance at month end",
  "የዓመቱ የተጣራ ፍሰት {v}": "Net cash flow this year {v}",
  "ወርሃዊ የገንዘብ ፍሰት · {y}": "Monthly cash flow · {y}",
  "የገባ": "Cash in",
  "የወጣ": "Cash out",
  "የመነሻ ካፒታል (ገንዘብ)": "Starting capital (cash)",
  "ደብተሩን ሲጀምሩ በእጅ/በባንክ የነበረ ገንዘብ፤ የካፒታልና የገንዘብ ሒሳብ መነሻ ነው።": "Cash you had when starting the ledger; the base for capital and cash balances.",
  "ባንክ": "Bank",
  "ገንዘብ ጨምር": "Add money",
  "በዕዳ ገንዘብ ጨምር": "Add money with debt",
  "ገንዘብ": "Amount",
  "ምክንያት": "Reason",
  "ድርጊት": "Actions",
  "በዕዳ": "With debt",
  "ያለ ዕዳ": "No debt",
  "ገና ገንዘብ አልተጨመረም።": "No money added yet.",
  "ይሰረዝ?": "Delete this entry?",
  "ይህ መዝገብ ከባንክ ይሰረዛል፤ ካፒታሉም ይቀየራል።": "This entry will be removed from the bank and the capital will change.",
  "በተሳካ ሁኔታ ተቀምጧል": "Saved successfully",
  "በተሳካ ሁኔታ ተስተካክሏል": "Edited successfully",
};
